### ISSUE TITLE
Cuadro Comparativo    1 "B"   Kevin Andrew

### ISSUE THREAD

**Issue by KevinOsorio23143** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-KevinOsorio23143#1]
[Metodo cientifico - Kevin osorio.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-KevinOsorio23143/files/9457613/Metodo.cientifico.-.Kevin.osorio.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
Presentación sencilla, pocas faltas de ortografía.

De acuerdo a la rúbrica, has obtenido un 18.3% del 20%

**Comment by josealfredo79** [comment]
BIen hecho y revisado..
